const skills = [
  "ReactJS",
  "Ruby On Rails",
  "Javascript (ES6 and Beyond)",
  "SQL",
  "NodeJS",
  "Ruby",
  "Command Line",
  "HTMl",
  "CSS",
  "Git / Github",
  "Gerrit",
  "Heroku",
  "Styled Components",
  "PostgreSQL",
  "Sidkiq",
  "React Router",
  "Context API",
  "Redux",
  ".Net Core",
  "Django",
  "Python",
]

export default skills;